---
title: "Worked Example: Interval Estimation"
runningheader: "Interval Estimation" # only for pdf output
subtitle: "An implementation in R Markdown" # only for html output
author: "Lombardi"
date: "`r Sys.Date()`"
output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html: default
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
```

# Interval Estimation

In **point estimation** a sample statistic is used to estimate a population
parameter. For example, the sample mean $\bar{x}$ is a point estimator of
the population mean $\mu$. Since a point estimator does not provide an 
exact value of the population parameter, an **interval estimate** is computed
by adding and subtracting a value, called the **margin of error**, to the point
estimate. 

```{marginfigure}
The general form of an interval estimate is: **point estimate $\pm$ margin of error**
```

The purpose of an interval estimate is to provide information about how close
the point estimate, provided by the sample, is to the value of the population
parameter. The general form of an interval estimate of a population mean $\mu$ is: $\bar{x}$ $\pm$ margin of error

# Interval Estimate for Population Mean: $\sigma$ Known

When the population standard deviation is known, formula 1 is used to 
calculate the interval estimate for the population mean where (1 - $\alpha$) is the **confidence coefficient** and $z_{\frac{\alpha}{2}}$ is the z value providing an area of $\frac{\alpha}{2}$ in the upper tail of the standard normal probability distribution.

```{marginfigure}
\LARGE
\begin{equation} 
    \bar{x} \pm z_{\frac{\alpha}{2}} \frac{\sigma}{\sqrt{n}}
\end{equation}

```  
\
**PROBLEM:** Given a sample mean $\bar{x}$ = 82, a population standard deviation 
$\sigma$ = 20, and a sample size n = 100, construct a 95% confidence interval.  

\
*Step 1*: Find $\alpha$

For a 95% confidence interval, the **confidence coefficient** is   
(1 - $\alpha$) = 0.95.
Therefore, $\alpha$ = 0.05.\
\
*Step 2*: Find the z-score associated with $\alpha$/2

Using the standard normal probability table, an area of $\alpha$/2 = 0.05/2 = 0.025
in the upper tail provides $z_.025$. = 1.96.\
\
*Step 3*: Substitute the values in the formula.

$82 \pm 1.96 \frac{20}{\sqrt{100}}$\
\
*Step 4*: Calculate the margin of error

$82 \pm 3.92$\

*Step 5*: Construct the confidence interval

Construct the 95% confidence interval of the population mean by subtracting the interval estimate from the 
sample mean $82-3.92$ = 78.08 and then by adding the interval estimate to 
the sample mean $82+3.92$ = 85.92.


# Interval Estimate for Population Mean: $\sigma$ Unknown

Sometime the population standard deviation is unknown when
constructing a confidence interval. In such cases, the sample data provides
an estimate for both $\mu$ and $\sigma$. When s is used to estimate $\sigma$, the 
margin of error and the interval estimate for the population mean are based 
on a probability distribution known as the **t distribution**. 

```{marginfigure}
**Degrees of freedom** is a parameter used with the t distribution. When the
t distribution is used in the computation of an interval estimate of a population
mean, the appropriate t distribution has n-1 degrees of freedom, where n
is the sample size.
```

To compute an interval estimate of $\mu$ for the $\sigma$ unknown case , the
sample standard deviation s is used to estimate $\sigma$ , and $z_.025$ is 
replaced by the t distribution value $t_.025$. Formula 2 is the general 
expression for an interval estimate of a population mean when $\sigma$ is
unknown where s is the sample standard deviation, (1-$\alpha$) is the confidence
coefficient, and $t_{\frac{\alpha}{2}}$ is the t value providing the area of 
$\alpha$/2 in the upper tail of the t distribution with n-1 degrees of freedom.

```{marginfigure}
\LARGE
\begin{equation} 
    \bar{x} \pm t_{\frac{\alpha}{2}} \frac{s}{\sqrt{n}}
\end{equation}

```  
\
**PROBLEM:** Given a sample mean $\bar{x}$ = 9312, sample standard deviation
s = 4007, and sample size n=70, construct a 95% confidence interval.
\
*Step 1*: Find $\alpha$

For a 95% confidence interval, the **confidence coefficient** is   
(1 - $\alpha$) = 0.95.
Therefore, $\alpha$ = 0.05.\
\
*Step 2*: Find the t value associated with $\alpha$/2

In this case, degrees of freedom = 69 because our sample size n = 70 (70-1). 
The t distribution table provides the appropriate value for $t_{\frac{\alpha}{2}}$.

The t value 1.995 is located at the intersection of row 69 (degrees of freedom) and 
column .025, the area for the upper tail.
\
*Step 3*: Substitute the values in the formula

Starting from the equation,

$\bar{x} \pm t_{\frac{\alpha}{2}} \frac{s}{\sqrt{n}}$

the formula after the substitutions is:

$9312 \pm 1.995 \frac{4007}{\sqrt{70}}$
\
*Step 4*: Calculate the margin of error

$9312 \pm 955$
\
*Step 5*: Construct the confidence interval

Construct the 95% confidence interval of the population mean by subtracting the interval estimate from the 
sample mean $9312-955$ = 8357 and then by adding the interval estimate to 
the sample mean $9312+955$ = 10,267.

